// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/S9S99/todo_list/ent/predicate"
	"github.com/S9S99/todo_list/ent/schema"
	"github.com/S9S99/todo_list/ent/todo"
)

// TodoUpdate is the builder for updating Todo entities.
type TodoUpdate struct {
	config
	hooks    []Hook
	mutation *TodoMutation
}

// Where appends a list predicates to the TodoUpdate builder.
func (tu *TodoUpdate) Where(ps ...predicate.Todo) *TodoUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetTitle sets the "title" field.
func (tu *TodoUpdate) SetTitle(s string) *TodoUpdate {
	tu.mutation.SetTitle(s)
	return tu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (tu *TodoUpdate) SetNillableTitle(s *string) *TodoUpdate {
	if s != nil {
		tu.SetTitle(*s)
	}
	return tu
}

// SetTag sets the "tag" field.
func (tu *TodoUpdate) SetTag(s string) *TodoUpdate {
	tu.mutation.SetTag(s)
	return tu
}

// SetNillableTag sets the "tag" field if the given value is not nil.
func (tu *TodoUpdate) SetNillableTag(s *string) *TodoUpdate {
	if s != nil {
		tu.SetTag(*s)
	}
	return tu
}

// SetBody sets the "body" field.
func (tu *TodoUpdate) SetBody(s string) *TodoUpdate {
	tu.mutation.SetBody(s)
	return tu
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (tu *TodoUpdate) SetNillableBody(s *string) *TodoUpdate {
	if s != nil {
		tu.SetBody(*s)
	}
	return tu
}

// ClearBody clears the value of the "body" field.
func (tu *TodoUpdate) ClearBody() *TodoUpdate {
	tu.mutation.ClearBody()
	return tu
}

// SetCompleted sets the "completed" field.
func (tu *TodoUpdate) SetCompleted(s schema.Status) *TodoUpdate {
	tu.mutation.SetCompleted(s)
	return tu
}

// SetNillableCompleted sets the "completed" field if the given value is not nil.
func (tu *TodoUpdate) SetNillableCompleted(s *schema.Status) *TodoUpdate {
	if s != nil {
		tu.SetCompleted(*s)
	}
	return tu
}

// ClearCompleted clears the value of the "completed" field.
func (tu *TodoUpdate) ClearCompleted() *TodoUpdate {
	tu.mutation.ClearCompleted()
	return tu
}

// SetProgress sets the "progress" field.
func (tu *TodoUpdate) SetProgress(u uint8) *TodoUpdate {
	tu.mutation.ResetProgress()
	tu.mutation.SetProgress(u)
	return tu
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (tu *TodoUpdate) SetNillableProgress(u *uint8) *TodoUpdate {
	if u != nil {
		tu.SetProgress(*u)
	}
	return tu
}

// AddProgress adds u to the "progress" field.
func (tu *TodoUpdate) AddProgress(u int8) *TodoUpdate {
	tu.mutation.AddProgress(u)
	return tu
}

// SetCreatedAt sets the "created_at" field.
func (tu *TodoUpdate) SetCreatedAt(t time.Time) *TodoUpdate {
	tu.mutation.SetCreatedAt(t)
	return tu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tu *TodoUpdate) SetNillableCreatedAt(t *time.Time) *TodoUpdate {
	if t != nil {
		tu.SetCreatedAt(*t)
	}
	return tu
}

// SetUpdatedAt sets the "updated_at" field.
func (tu *TodoUpdate) SetUpdatedAt(t time.Time) *TodoUpdate {
	tu.mutation.SetUpdatedAt(t)
	return tu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tu *TodoUpdate) SetNillableUpdatedAt(t *time.Time) *TodoUpdate {
	if t != nil {
		tu.SetUpdatedAt(*t)
	}
	return tu
}

// Mutation returns the TodoMutation object of the builder.
func (tu *TodoUpdate) Mutation() *TodoMutation {
	return tu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TodoUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TodoUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TodoUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TodoUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tu *TodoUpdate) check() error {
	if v, ok := tu.mutation.Progress(); ok {
		if err := todo.ProgressValidator(v); err != nil {
			return &ValidationError{Name: "progress", err: fmt.Errorf(`ent: validator failed for field "Todo.progress": %w`, err)}
		}
	}
	return nil
}

func (tu *TodoUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(todo.Table, todo.Columns, sqlgraph.NewFieldSpec(todo.FieldID, field.TypeInt))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.Title(); ok {
		_spec.SetField(todo.FieldTitle, field.TypeString, value)
	}
	if value, ok := tu.mutation.Tag(); ok {
		_spec.SetField(todo.FieldTag, field.TypeString, value)
	}
	if value, ok := tu.mutation.Body(); ok {
		_spec.SetField(todo.FieldBody, field.TypeString, value)
	}
	if tu.mutation.BodyCleared() {
		_spec.ClearField(todo.FieldBody, field.TypeString)
	}
	if value, ok := tu.mutation.Completed(); ok {
		_spec.SetField(todo.FieldCompleted, field.TypeBool, value)
	}
	if tu.mutation.CompletedCleared() {
		_spec.ClearField(todo.FieldCompleted, field.TypeBool)
	}
	if value, ok := tu.mutation.Progress(); ok {
		_spec.SetField(todo.FieldProgress, field.TypeUint8, value)
	}
	if value, ok := tu.mutation.AddedProgress(); ok {
		_spec.AddField(todo.FieldProgress, field.TypeUint8, value)
	}
	if value, ok := tu.mutation.CreatedAt(); ok {
		_spec.SetField(todo.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := tu.mutation.UpdatedAt(); ok {
		_spec.SetField(todo.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{todo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// TodoUpdateOne is the builder for updating a single Todo entity.
type TodoUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TodoMutation
}

// SetTitle sets the "title" field.
func (tuo *TodoUpdateOne) SetTitle(s string) *TodoUpdateOne {
	tuo.mutation.SetTitle(s)
	return tuo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (tuo *TodoUpdateOne) SetNillableTitle(s *string) *TodoUpdateOne {
	if s != nil {
		tuo.SetTitle(*s)
	}
	return tuo
}

// SetTag sets the "tag" field.
func (tuo *TodoUpdateOne) SetTag(s string) *TodoUpdateOne {
	tuo.mutation.SetTag(s)
	return tuo
}

// SetNillableTag sets the "tag" field if the given value is not nil.
func (tuo *TodoUpdateOne) SetNillableTag(s *string) *TodoUpdateOne {
	if s != nil {
		tuo.SetTag(*s)
	}
	return tuo
}

// SetBody sets the "body" field.
func (tuo *TodoUpdateOne) SetBody(s string) *TodoUpdateOne {
	tuo.mutation.SetBody(s)
	return tuo
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (tuo *TodoUpdateOne) SetNillableBody(s *string) *TodoUpdateOne {
	if s != nil {
		tuo.SetBody(*s)
	}
	return tuo
}

// ClearBody clears the value of the "body" field.
func (tuo *TodoUpdateOne) ClearBody() *TodoUpdateOne {
	tuo.mutation.ClearBody()
	return tuo
}

// SetCompleted sets the "completed" field.
func (tuo *TodoUpdateOne) SetCompleted(s schema.Status) *TodoUpdateOne {
	tuo.mutation.SetCompleted(s)
	return tuo
}

// SetNillableCompleted sets the "completed" field if the given value is not nil.
func (tuo *TodoUpdateOne) SetNillableCompleted(s *schema.Status) *TodoUpdateOne {
	if s != nil {
		tuo.SetCompleted(*s)
	}
	return tuo
}

// ClearCompleted clears the value of the "completed" field.
func (tuo *TodoUpdateOne) ClearCompleted() *TodoUpdateOne {
	tuo.mutation.ClearCompleted()
	return tuo
}

// SetProgress sets the "progress" field.
func (tuo *TodoUpdateOne) SetProgress(u uint8) *TodoUpdateOne {
	tuo.mutation.ResetProgress()
	tuo.mutation.SetProgress(u)
	return tuo
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (tuo *TodoUpdateOne) SetNillableProgress(u *uint8) *TodoUpdateOne {
	if u != nil {
		tuo.SetProgress(*u)
	}
	return tuo
}

// AddProgress adds u to the "progress" field.
func (tuo *TodoUpdateOne) AddProgress(u int8) *TodoUpdateOne {
	tuo.mutation.AddProgress(u)
	return tuo
}

// SetCreatedAt sets the "created_at" field.
func (tuo *TodoUpdateOne) SetCreatedAt(t time.Time) *TodoUpdateOne {
	tuo.mutation.SetCreatedAt(t)
	return tuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tuo *TodoUpdateOne) SetNillableCreatedAt(t *time.Time) *TodoUpdateOne {
	if t != nil {
		tuo.SetCreatedAt(*t)
	}
	return tuo
}

// SetUpdatedAt sets the "updated_at" field.
func (tuo *TodoUpdateOne) SetUpdatedAt(t time.Time) *TodoUpdateOne {
	tuo.mutation.SetUpdatedAt(t)
	return tuo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tuo *TodoUpdateOne) SetNillableUpdatedAt(t *time.Time) *TodoUpdateOne {
	if t != nil {
		tuo.SetUpdatedAt(*t)
	}
	return tuo
}

// Mutation returns the TodoMutation object of the builder.
func (tuo *TodoUpdateOne) Mutation() *TodoMutation {
	return tuo.mutation
}

// Where appends a list predicates to the TodoUpdate builder.
func (tuo *TodoUpdateOne) Where(ps ...predicate.Todo) *TodoUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TodoUpdateOne) Select(field string, fields ...string) *TodoUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Todo entity.
func (tuo *TodoUpdateOne) Save(ctx context.Context) (*Todo, error) {
	return withHooks(ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TodoUpdateOne) SaveX(ctx context.Context) *Todo {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TodoUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TodoUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tuo *TodoUpdateOne) check() error {
	if v, ok := tuo.mutation.Progress(); ok {
		if err := todo.ProgressValidator(v); err != nil {
			return &ValidationError{Name: "progress", err: fmt.Errorf(`ent: validator failed for field "Todo.progress": %w`, err)}
		}
	}
	return nil
}

func (tuo *TodoUpdateOne) sqlSave(ctx context.Context) (_node *Todo, err error) {
	if err := tuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(todo.Table, todo.Columns, sqlgraph.NewFieldSpec(todo.FieldID, field.TypeInt))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Todo.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, todo.FieldID)
		for _, f := range fields {
			if !todo.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != todo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.Title(); ok {
		_spec.SetField(todo.FieldTitle, field.TypeString, value)
	}
	if value, ok := tuo.mutation.Tag(); ok {
		_spec.SetField(todo.FieldTag, field.TypeString, value)
	}
	if value, ok := tuo.mutation.Body(); ok {
		_spec.SetField(todo.FieldBody, field.TypeString, value)
	}
	if tuo.mutation.BodyCleared() {
		_spec.ClearField(todo.FieldBody, field.TypeString)
	}
	if value, ok := tuo.mutation.Completed(); ok {
		_spec.SetField(todo.FieldCompleted, field.TypeBool, value)
	}
	if tuo.mutation.CompletedCleared() {
		_spec.ClearField(todo.FieldCompleted, field.TypeBool)
	}
	if value, ok := tuo.mutation.Progress(); ok {
		_spec.SetField(todo.FieldProgress, field.TypeUint8, value)
	}
	if value, ok := tuo.mutation.AddedProgress(); ok {
		_spec.AddField(todo.FieldProgress, field.TypeUint8, value)
	}
	if value, ok := tuo.mutation.CreatedAt(); ok {
		_spec.SetField(todo.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := tuo.mutation.UpdatedAt(); ok {
		_spec.SetField(todo.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Todo{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{todo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
